// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: rbac.proto

package rbacpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignPermissionToRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleID        int64                  `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty"`
	PermissionID  int64                  `protobuf:"varint,2,opt,name=permissionID,proto3" json:"permissionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionToRoleRequest) Reset() {
	*x = AssignPermissionToRoleRequest{}
	mi := &file_rbac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionToRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionToRoleRequest) ProtoMessage() {}

func (x *AssignPermissionToRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionToRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignPermissionToRoleRequest) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *AssignPermissionToRoleRequest) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *AssignPermissionToRoleRequest) GetPermissionID() int64 {
	if x != nil {
		return x.PermissionID
	}
	return 0
}

type AssignRoleToUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleID        int64                  `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleToUserRequest) Reset() {
	*x = AssignRoleToUserRequest{}
	mi := &file_rbac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleToUserRequest) ProtoMessage() {}

func (x *AssignRoleToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleToUserRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleToUserRequest) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{1}
}

func (x *AssignRoleToUserRequest) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *AssignRoleToUserRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type CheckUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserRoleRequest) Reset() {
	*x = CheckUserRoleRequest{}
	mi := &file_rbac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserRoleRequest) ProtoMessage() {}

func (x *CheckUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserRoleRequest.ProtoReflect.Descriptor instead.
func (*CheckUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{2}
}

func (x *CheckUserRoleRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *CheckUserRoleRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type CheckUserRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasRole       bool                   `protobuf:"varint,1,opt,name=hasRole,proto3" json:"hasRole,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserRoleResponse) Reset() {
	*x = CheckUserRoleResponse{}
	mi := &file_rbac_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserRoleResponse) ProtoMessage() {}

func (x *CheckUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserRoleResponse.ProtoReflect.Descriptor instead.
func (*CheckUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{3}
}

func (x *CheckUserRoleResponse) GetHasRole() bool {
	if x != nil {
		return x.HasRole
	}
	return false
}

var File_rbac_proto protoreflect.FileDescriptor

const file_rbac_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rbac.proto\x12\x04rbac\x1a\x1bgoogle/protobuf/empty.proto\"[\n" +
	"\x1dAssignPermissionToRoleRequest\x12\x16\n" +
	"\x06roleID\x18\x01 \x01(\x03R\x06roleID\x12\"\n" +
	"\fpermissionID\x18\x02 \x01(\x03R\fpermissionID\"I\n" +
	"\x17AssignRoleToUserRequest\x12\x16\n" +
	"\x06roleID\x18\x01 \x01(\x03R\x06roleID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x03R\x06userID\"K\n" +
	"\x14CheckUserRoleRequest\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x03R\x06userID\"1\n" +
	"\x15CheckUserRoleResponse\x12\x18\n" +
	"\ahasRole\x18\x01 \x01(\bR\ahasRole2\xf9\x01\n" +
	"\vRBACService\x12U\n" +
	"\x16AssignPermissionToRole\x12#.rbac.AssignPermissionToRoleRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x10AssignRoleToUser\x12\x1d.rbac.AssignRoleToUserRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\rCheckUserRole\x12\x1a.rbac.CheckUserRoleRequest\x1a\x1b.rbac.CheckUserRoleResponseB-Z+abbassmortazavi/go-microservice/rbac;rbacpbb\x06proto3"

var (
	file_rbac_proto_rawDescOnce sync.Once
	file_rbac_proto_rawDescData []byte
)

func file_rbac_proto_rawDescGZIP() []byte {
	file_rbac_proto_rawDescOnce.Do(func() {
		file_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rbac_proto_rawDesc), len(file_rbac_proto_rawDesc)))
	})
	return file_rbac_proto_rawDescData
}

var file_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rbac_proto_goTypes = []any{
	(*AssignPermissionToRoleRequest)(nil), // 0: rbac.AssignPermissionToRoleRequest
	(*AssignRoleToUserRequest)(nil),       // 1: rbac.AssignRoleToUserRequest
	(*CheckUserRoleRequest)(nil),          // 2: rbac.CheckUserRoleRequest
	(*CheckUserRoleResponse)(nil),         // 3: rbac.CheckUserRoleResponse
	(*emptypb.Empty)(nil),                 // 4: google.protobuf.Empty
}
var file_rbac_proto_depIdxs = []int32{
	0, // 0: rbac.RBACService.AssignPermissionToRole:input_type -> rbac.AssignPermissionToRoleRequest
	1, // 1: rbac.RBACService.AssignRoleToUser:input_type -> rbac.AssignRoleToUserRequest
	2, // 2: rbac.RBACService.CheckUserRole:input_type -> rbac.CheckUserRoleRequest
	4, // 3: rbac.RBACService.AssignPermissionToRole:output_type -> google.protobuf.Empty
	4, // 4: rbac.RBACService.AssignRoleToUser:output_type -> google.protobuf.Empty
	3, // 5: rbac.RBACService.CheckUserRole:output_type -> rbac.CheckUserRoleResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rbac_proto_init() }
func file_rbac_proto_init() {
	if File_rbac_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rbac_proto_rawDesc), len(file_rbac_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rbac_proto_goTypes,
		DependencyIndexes: file_rbac_proto_depIdxs,
		MessageInfos:      file_rbac_proto_msgTypes,
	}.Build()
	File_rbac_proto = out.File
	file_rbac_proto_goTypes = nil
	file_rbac_proto_depIdxs = nil
}
