apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

  # ConfigMaps - Secrets

  # Databases

  # Message Queue

  # Services

#- configs/secrets.yaml
resources:
- api-gateway/deployment.yaml
- api-gateway/service.yaml
- auth-service/deployment.yaml
- auth-service/service.yaml
- postgres-service/deployment.yaml
- postgres-service/service.yaml
- postgres-service/pvc.yaml
- rabbitmq-service/deployment.yaml
- rabbitmq-service/service.yaml
- notification-service/deployment.yaml


labels:
- pairs:
    env: production
images:
- name: abbass69/api-gateway
  newTag: 9bcd0d2a0be8a59743e84d625feb71994dc7d61f
- name: abbass69/auth-service
  newTag: 9bcd0d2a0be8a59743e84d625feb71994dc7d61f
- name: abbass69/notification-service
  newTag: 9bcd0d2a0be8a59743e84d625feb71994dc7d61f
