apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local

  # ConfigMaps - Secrets

  # Databases

  # Message Queue

  # Services

#- configs/secrets.yaml
resources:
- api-gateway/deployment.yaml
- api-gateway/service.yaml
- auth-service/deployment.yaml
- auth-service/service.yaml
- postgres-service/deployment.yaml
- postgres-service/service.yaml
- postgres-service/pvc.yaml
- rabbitmq-service/deployment.yaml
- rabbitmq-service/service.yaml
- notification-service/deployment.yaml

labels:
- pairs:
    env: local
images:
- name: api-gateway
  newTag: 138c894c3820b63cec37884da734837e7c14cc1b
- name: auth-service
  newTag: 138c894c3820b63cec37884da734837e7c14cc1b
- name: abbass69/notification-service
  newTag: b478a73615b79ca549db645bb6ffebb3343703c5
