apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce  # فقط یک pod می‌تواند همزمان write کند
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard