# argocd/apps/argocd-app.yml (یا microservice-production.yaml)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abbassmortazavi/go-microservice.git
    targetRevision: HEAD
    path: infra/k8s/production  # ✅ مسیر جدید
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true