apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
