apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

  # ConfigMaps - Secrets

  # Databases

  # Message Queue

# Services

#- configs/secrets.yaml
resources:
- api-gateway/deployment.yaml
- api-gateway/service.yaml
- auth-service/deployment.yaml
- auth-service/service.yaml
- postgres-service/deployment.yaml
- postgres-service/service.yaml
- postgres-service/pvc.yaml
- rabbitmq-service/deployment.yaml
- rabbitmq-service/service.yaml
- notification-service/deployment.yaml

labels:
- pairs:
    env: development
images:
- name: abbass69/api-gateway
  newTag: d6bd39bcd396bd2e04305e1c4926329cfba3fbfc
- name: abbass69/auth-service
  newTag: b478a73615b79ca549db645bb6ffebb3343703c5
- name: abbass69/notification-service
  newTag: d6bd39bcd396bd2e04305e1c4926329cfba3fbfc
