apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
- api-gateway/deployment.yaml
- api-gateway/service.yaml
- auth-service/deployment.yaml
- auth-service/service.yaml
- postgres-service/deployment.yaml
- postgres-service/service.yaml
- postgres-service/pvc.yaml
- rabbitmq-service/deployment.yaml
- rabbitmq-service/service.yaml

labels:
- pairs:
    env: development

images:
- name: api-gateway
  newTag: 58a82fc0d26b2b1766858d12bf3762bb954f9315
- name: auth-service
  newTag: 58a82fc0d26b2b1766858d12bf3762bb954f9315
