apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

  # ConfigMaps - Secrets

  # Databases

  # Message Queue

# Services

#- configs/secrets.yaml
resources:
- api-gateway/deployment.yaml
- api-gateway/service.yaml
- auth-service/deployment.yaml
- auth-service/service.yaml
- postgres-service/deployment.yaml
- postgres-service/service.yaml
- postgres-service/pvc.yaml
- rabbitmq-service/deployment.yaml
- rabbitmq-service/service.yaml
- notification-service/deployment.yaml
- post-service/deployment.yaml
- post-service/service.yaml

labels:
- pairs:
    env: development
images:
- name: abbass69/api-gateway
  newTag: eadc44eed1b7056a3fe687e87e55e8451f6a2ad1
- name: abbass69/auth-service
  newTag: eadc44eed1b7056a3fe687e87e55e8451f6a2ad1
- name: abbass69/notification-service
  newTag: eadc44eed1b7056a3fe687e87e55e8451f6a2ad1
- name: abbass69/post-service
