apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd   # ⚠️ حتماً namespace خود argo
spec:
  project: default

  source:
    repoURL: https://github.com/abbassmortazavi/go-microservice
    targetRevision: main
    path: infra/development/k8s
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
