name: Run Tests

on:
  workflow_call:
    inputs:
      environment:        # ← اضافه کن
        required: false
        type: string
        default: 'development'
  pull_request:
    branches: [develop, main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run tests
        run: go test ./...